### ISSUE TITLE
FR: Support Widgets

### ISSUE THREAD

**Issue by BeastyBlacksmith** [davidanthoff/Electron.jl#100]
I'd like to use `Interact.jl` widgets with an Electron window, but there isn't a method for `load` that accepts a `Widget`
```julia
using Electron, Interact
win = Window()
ui = button()
load(win, ui)
```

**Comment by davidanthoff** [comment]
I can see how this would be useful, but I don't think it belongs in this package here. The idea for this package is to keep things lean, not have many dependencies, not pick "one" UI framework etc. It really is meant as just a very thin wrapper around the electron functionality. I could easily see another package that depends on both Electron and Interact and provides this kind of functionality.
