### ISSUE TITLE
Depend upon FilePathsBase instead of FilePaths

### ISSUE THREAD

**Issue by frankier** [davidanthoff/Electron.jl#128]
Might it be possible to depend upon FilePathsBase rather than FilePaths? I'm having some problems with FilePaths and this might help, plus it could improve compilation speed.

Let me know if you would like me to put together a PR.

**Comment by frankier** [comment]
I think this would help remove this hack from Makie: https://github.com/MakieOrg/Makie.jl/blob/ae8c1a455b20586febab682bc709a4ddd60d935f/src/Makie.jl#L15-L20

**Comment by davidanthoff** [comment]
We depend on FilePaths.jl because we need the integration with URIs.jl, which is not part of FilePathsBase.jl...

**Comment by SimonDanisch** [comment]
Is that absolutely necessary, or could we simply extract some functions and handle things a bit more manually? 
FilePaths seems to be pretty horrible for load times and I didn't realize how much it was until now (from ~4s to 6s load time in Makie).

**Comment by frankier** [comment]
Yeah FilePaths.jl is effectively deprecated. I've fixed my old PR here: https://github.com/davidanthoff/Electron.jl/pull/140
