### ISSUE TITLE
Add demo website or make example repo

### ISSUE THREAD

**Issue by djsegal** [davidanthoff/Electron.jl#5]
Do you have a demo site (or example github repo) off-hand that would allow someone to play with this before they download it?

Pretty interested in monkeying around with it. Just don't know where to start

**Comment by davidanthoff** [comment]
https://github.com/davidanthoff/DataVoyager.jl uses this under the hood, but that is relatively involved.

**Comment by davidanthoff** [comment]
Oh, and also https://github.com/davidanthoff/ElectronDisplay.jl, but that is at best half-finished.

**Comment by davidanthoff** [comment]
I've now added both of these to the README.
