### ISSUE TITLE
no show

### ISSUE THREAD

**Issue by PaulSoderlind** [davidanthoff/Electron.jl#6]
on windows 10/Julia 0.6.2. That is, the electron window pops up but no contents are show. To replicate:
```
w = Window(URI("file://test.html"))
```

Edit: this works: w = Window(URI("file:///test.html")). Sorry for the noise

2nd thing: there are two small typos in the readme.md: it says URI("file://main.html). I guess it should be URI("file://main.html")

**Comment by davidanthoff** [comment]
Thanks, the typos are now fixed!
