### ISSUE TITLE
Error: Can't initialize nvrm channel

### ISSUE THREAD

**Issue by ianshmean** [davidanthoff/Electron.jl#64]
I'm testing on an aarch64 system. Tests pass but there are many reports of
```
Error: Can't initialize nvrm channel
```
@davidanthoff is that an actual error that's uncaught by tests?

**Comment by davidanthoff** [comment]
I have no idea :) Do these error messages show up while you run tests, i.e. tests pass and at the same time you get these messages?

I don't even know what a nvrm channel is, to be honest...

**Comment by ianshmean** [comment]
Yeah, during the tests I see ~20 of these printed, then all tests pass

**Comment by ianshmean** [comment]
Looks like it's an open nvidia issue that anything web suffers from https://devtalk.nvidia.com/default/topic/1038639/jetson-tx2/error-can-t-initialize-nvrm-channel/post/5355677/#5355677
