### ISSUE TITLE
TableView support (or similar)?

### ISSUE THREAD

**Issue by ianshmean** [davidanthoff/Electron.jl#76]
Is it possible to show a [TableView](https://github.com/JuliaComputing/TableView.jl) via Electron? i.e. instead of via Blink. I'm trying to avoid BinDeps builds

Or is there a similar alternative? I want to display a table that updates async, with scrolling as a minimum. Sorting & filtering would be nice

**Comment by davidanthoff** [comment]
https://github.com/queryverse/ElectronDisplay.jl should be your friend, it has a table/grid viewer and is based on this package here.

It does not have the lazy viewing stuff that TableView has, though. Would be good to add that at some point.

**Comment by ianshmean** [comment]
Great! I got a DataFrame to view, but couldn't figure out how to get the window to update when the DataFrame changes. Is that possible/simple? (Happy to open an issue on that repo if better)

**Comment by davidanthoff** [comment]
Ah, no, there is no live update feature: it takes a snapshop of the DataFrame and then shows that, with no connection left. I don't think the machinery for the kind of scenario you explain is there right now, for example there is no way that the DataFrame could "tell" the view that it was updated, AFAIK.
