### ISSUE TITLE
404 on JuliaHub for this package

### ISSUE THREAD

**Issue by rapus95** [davidanthoff/Electron.jl#89]
https://juliahub.com/ui/Packages?q=electron following the first link there
![image](https://user-images.githubusercontent.com/5960902/107309354-91423b00-6a8a-11eb-983a-d41501d482d5.png)
i.e. https://juliahub.com/ui/Packages/Electron/L6ESt/3.1.1
results in a 404
![image](https://user-images.githubusercontent.com/5960902/107309403-a919bf00-6a8a-11eb-89a9-414de3e039c3.png)

**Comment by davidanthoff** [comment]
Hm, I think this must be a bug with JuliaHub, I don't even know what it is supposed to do :)

@pfitzseb, are you involved with JuliaHub and know what is going on there?

**Comment by pfitzseb** [comment]
Will figure out what's going on there. In the future, please just open this kind of issue at https://github.com/JuliaComputing/JuliaHub!
