### ISSUE TITLE
Cleanly exiting or quitting

### ISSUE THREAD

**Issue by Immortalin** [davidanthoff/Electron.jl#97]
How do you exit or close the electron process? Exiting julia raises an error if the electron process is still running.

**Comment by ettersi** [comment]
I think this error arises as follows:

- User shuts down Julia. 
- Julia tells Electron to shut down (by closing the `connection` pipe)
- Electron tries to tell Julia that it's shutting down (via the `sysnotify` pipe)
- If Julia shuts down faster than Electron, then the `sysnotify` pipe is already closed by the time Electron tries to use it.

**Comment by hhaensel** [comment]
Closing the electron process is
```julia
app = Application()
close(app)
```
or
```julia
win = Window()
close(win.app)
```

**Comment by Immortalin** [comment]
Can we block Julia from exiting until Electron has cleanly closed?
